### Get all Contacts
GET http://localhost:3000/contacts/
###

### Get one contact Lindy
GET http://localhost:3000/contacts/65ab727a15ad91890852ae2d
###

### Get one Contact Eddy
GET http://localhost:3000/contacts/65ab727a15ad91890852ae2e
###

### Get one Contact Max
GET http://localhost:3000/contacts/65ab727a15ad91890852ae2f



### Create New Contact
POST http://localhost:3000/contacts HTTP/1.1 
content-type:application/json

{
    "firstName":"DELETE ME",
    "lastName":"Moes",
    "email":"imoes@test.com",
    "favoriteColor":"red",
    "birthday":"01/01/2000"
    
}
### Update One Contact
PUT http://localhost:3000/contacts/65ab727a15ad91890852ae2e HTTP/1.1
Content-Type:application/json

{
    "firstName":"Edward",
    "lastName":"Moes",
    "email":"emoes@test.com",
    "favoriteColor":"blue",
    "birthday":"01/01/2000"
}

### Delete One Contact 
DELETE http://localhost:3000/contacts/65b4b6336f30bb7e67ac0da4 HTTP/1.1
Content-Type:application/json
###



//This section is for render links 
### Get all Contacts
GET https://cse-341-webservices.onrender.com/contacts/
###

### Get one contact Lindy
GET https://cse-341-webservices.onrender.com/contacts/65ab727a15ad91890852ae2d
###

### Get one Contact Eddy
GET https://cse-341-webservices.onrender.com/contacts/65ab727a15ad91890852ae2e
###

### Get one Contact Max
GET https://cse-341-webservices.onrender.com/contacts/65ab727a15ad91890852ae2f


### Create New Contact
POST https://cse-341-webservices.onrender.com/contacts HTTP/1.1 
content-type:application/json

{
    "firstName":"DELETE ME",
    "lastName":"Moes",
    "email":"imoes@test.com",
    "favoriteColor":"red",
    "birthday":"01/01/2000"
    
}


### Update one contact

PUT https://cse-341-webservices.onrender.com/contacts/65ab727a15ad91890852ae2e HTTP/1.1
Content-Type:application/json

{
    "firstName":"Edward",
    "lastName":"Moes",
    "email":"emoes@test.com",
    "favoriteColor":"blue",
    "birthday":"01/01/2000"
}

### Delete One Contact by ID
DELETE https://cse-341-webservices.onrender.com/contacts/65b4b87b966f88eb1f2d60f7 HTTP/1.1
Content-Type:application/json
###